from .academy_3_vs_1_with_keeper import Academy_3_vs_1_with_Keeper
from .academy_counterattack_easy import Academy_Counterattack_Easy
from .academy_pass_and_shoot_with_keeper import Academy_Pass_and_Shoot_with_Keeper