# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 100000

runner: "parallel"
run: "interval_run"
batch_size_run: 8
buffer_size: 5000 
batch_size: 128
optimizer: 'adam'

t_max: 10050000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
mac: "group_mac"
agent: "n_group"
agent_output_type: q

learner: "group_learner"
mixer: "group"
mixing_embed_dim: 32
hypernet_embed: 32
grouping_hypernet_embed: 32

lr: 0.001                           # Learning rate for agents
td_lambda: 0.6
optimizer: 'adam'
group: null                         # initial group [[0,...,n]]
change_group_interval: 100000
change_group_batch_num: 4           # change group data 256*4
change_group_batch_size: 256
change_group_value: 0.7             # change group when w1 < average * change_group_value

lasso_alpha_anneal_time: 100000
lasso_alpha_start: 0.005
lasso_alpha_anneal: 0.96
sd_alpha: 0.005

name: "group_env=8_adam_td_lambda"